name: Kickstart Reporting Workflow
on: [workflow_dispatch, push, pull_request]

jobs:
  call-report-script:
    uses: teamkfinteg/reportscripts/.github/workflows/basic.yml@main
    secrets: 
      token: ${{ secrets.PRIVATE_REPO_TEST }}
